service: aws-serverless
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource: 
        - arn:aws:dynamodb:us-east-1:103650216262:table/SubastasTable
        - !Join ['/', [ arn:aws:dynamodb:us-east-1:103650216262:table/SubastasTable, 'index', 'statusFechaFinIndex' ]]

resources:
  Resources:
    SubastasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubastasTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
          - AttributeName: fechaFin
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: statusFechaFinIndex
            KeySchema:
              - AttributeName: status
                KeyType: HASH
              - AttributeName: fechaFin
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL                
        BillingMode: PAY_PER_REQUEST

functions:
  crearSubasta:
    handler: src/handlers/crearSubasta.handler
    events:
      - http:
          path: /subasta
          method: POST
          authorizer: ${self:custom.authorizer}
  listarSubastas:
    handler: src/handlers/listarSubastas.handler
    events:
      - http:
          path: /subastas
          method: GET
          authorizer: ${self:custom.authorizer}
  obtenerSubasta:
    handler: src/handlers/obtenerSubasta.handler
    events:
      - http:
          path: /subasta/{id}
          method: GET
          authorizer: ${self:custom.authorizer}
  hacerOferta:
    handler: src/handlers/hacerOferta.handler
    events:
      - http:
          path: /subasta/{id}/ofertar
          method: PATCH
          authorizer: ${self:custom.authorizer}
  procesarSubastas:
    handler: src/handlers/procesarSubastas.handler
    #events:
      #- schedule: rate(1 minute)
          
custom:
  authorizer: arn:aws:lambda:us-east-1:103650216262:function:auth-serverless-dev-auth
  bundle:
    linting: false
